<?php
include("includes/dominio.php");
?>
<!DOCTYPE html>
<html>
	<head>

		<!-- Basic -->
		<meta charset="utf-8">
		<title>Porto - Responsive HTML5 Template 3.7.0</title>		
		<meta name="keywords" content="HTML5 Template" />
		<meta name="description" content="Porto - Responsive HTML5 Template">
		<meta name="author" content="okler.net">

		<!-- Mobile Metas -->
		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<!-- Web Fonts  -->
		<link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800%7CShadows+Into+Light" rel="stylesheet" type="text/css">
		
        
		<!-- Vendor CSS -->
		<link rel="stylesheet" href="<?php echo $dominio;?>/vendor/bootstrap/bootstrap.css">
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
		
        
        <link rel="stylesheet" href="<?php echo $dominio;?>/vendor/owlcarousel/owl.carousel.min.css" media="screen">
		<link rel="stylesheet" href="<?php echo $dominio;?>/vendor/owlcarousel/owl.theme.default.min.css" media="screen">
		<link rel="stylesheet" href="<?php echo $dominio;?>/vendor/magnific-popup/magnific-popup.css" media="screen">

		<!-- Theme CSS -->
		<link rel="stylesheet" href="<?php echo $dominio;?>/css/theme.css">
		<link rel="stylesheet" href="<?php echo $dominio;?>/css/theme-elements.css">
		<link rel="stylesheet" href="<?php echo $dominio;?>/css/theme-blog.css">
		<link rel="stylesheet" href="<?php echo $dominio;?>/css/theme-shop.css">
		<link rel="stylesheet" href="<?php echo $dominio;?>/css/theme-animate.css">
		

		<!-- Skin CSS -->
		<link rel="stylesheet" href="<?php echo $dominio;?>/css/skins/default.css">

		<!-- Theme Custom CSS -->
		<link rel="stylesheet" href="<?php echo $dominio;?>/css/custom.css">

		<!-- Head Libs -->
		<script src="<?php echo $dominio;?>/vendor/modernizr/modernizr.js"></script>

		<!--[if IE]>
			<link rel="stylesheet" href="<?php echo $dominio;?>/css/ie.css">
		<![endif]-->

		<!--[if lte IE 8]>
			<script src="<?php echo $dominio;?>/vendor/respond/respond.js"></script>
			<script src="<?php echo $dominio;?>/vendor/excanvas/excanvas.js"></script>
		<![endif]-->

	</head>
	<body>
		<div class="body">
			
			<?php include('includes/head.php');?>

			<div role="main" class="main">
            <?php echo $this->content; ?>
           </div>
 
			<?php include('includes/footer.php');?>
            
		</div>

		<!-- Vendor -->
		<script src="<?php echo $dominio;?>/vendor/jquery/jquery.js"></script>
		<script src="<?php echo $dominio;?>/vendor/jquery.appear/jquery.appear.js"></script>
		<script src="<?php echo $dominio;?>/vendor/jquery.easing/jquery.easing.js"></script>
		<script src="<?php echo $dominio;?>/vendor/jquery-cookie/jquery-cookie.js"></script>
		<script src="<?php echo $dominio;?>/vendor/bootstrap/bootstrap.js"></script>
		<script src="<?php echo $dominio;?>/vendor/common/common.js"></script>
		<script src="<?php echo $dominio;?>/vendor/jquery.validation/jquery.validation.js"></script>
		<script src="<?php echo $dominio;?>/vendor/jquery.stellar/jquery.stellar.js"></script>
		<script src="<?php echo $dominio;?>/vendor/jquery.easy-pie-chart/jquery.easy-pie-chart.js"></script>
		<script src="<?php echo $dominio;?>/vendor/jquery.gmap/jquery.gmap.js"></script>
		<script src="<?php echo $dominio;?>/vendor/isotope/jquery.isotope.js"></script>
		<script src="<?php echo $dominio;?>/vendor/owlcarousel/owl.carousel.js"></script>
		<script src="<?php echo $dominio;?>/vendor/jflickrfeed/jflickrfeed.js"></script>
		<script src="<?php echo $dominio;?>/vendor/magnific-popup/jquery.magnific-popup.js"></script>
		<script src="<?php echo $dominio;?>/vendor/vide/vide.js"></script>
		
		<!-- Theme Base, Components and Settings -->
		<script src="<?php echo $dominio;?>/js/theme.js"></script>
		
		<!-- Specific Page Vendor and Views -->
		<script src="js/views/view.contact.js"></script>

		<!-- Theme Custom -->
		<script src="<?php echo $dominio;?>/js/custom.js"></script>
		
		<!-- Theme Initialization Files -->
		<script src="<?php echo $dominio;?>/js/theme.init.js"></script>
		
		<script src="<?php echo $dominio;?>/js/treatments.js"></script>
		
        		<script src="http://maps.google.com/maps/api/js?sensor=false"></script>
		<script>

			/*
			Map Settings

				Find the Latitude and Longitude of your address:
					- http://universimmedia.pagesperso-orange.fr/geo/loc.htm
					- http://www.findlatitudeandlongitude.com/find-address-from-latitude-and-longitude/

			*/

			// Map Markers
			var mapMarkers = [{
				address: "<strong>Helbor Offices Vila Rica</strong><br>Avenida Conselheiro Nébias, 754/756 - Boqueirão, Santos - SP",
				html: "<strong>Helbor Offices Vila Rica</strong><br>Avenida Conselheiro Nébias, 756 - Boqueirão, Santos - SP",
				icon: {
					image: "/img/pin.png",
					iconsize: [26, 46],
					iconanchor: [12, 46]
				},
				popup: true
			}];

			// Map Initial Location
			var initLatitude = -23.9676592;
			var initLongitude = -46.3235161;

			// Map Extended Settings
			var mapSettings = {
				controls: {
					draggable: true,
					panControl: true,
					zoomControl: true,
					mapTypeControl: true,
					scaleControl: true,
					streetViewControl: true,
					overviewMapControl: true
				},
				scrollwheel: false,
				markers: mapMarkers,
				latitude: initLatitude,
				longitude: initLongitude,
				zoom: 16
			};

			var map = $("#googlemaps").gMap(mapSettings);

			// Map Center At
			var mapCenterAt = function(options, e) {
				e.preventDefault();
				$("#googlemaps").gMap("centerAt", options);
			}

		</script>

            
        
		<?php include('includes/analytics.php');?>
		

	</body>
</html>